plugins:
        zendesk_enabled:
                default: false
                client: true
        zendesk_url:
                default: ''
        zendesk_username:
                default: ''
        zendesk_token:
                default: ''

